"""initial_schema

Revision ID: 0292f11fadf5
Revises:
Create Date: 2026-05-20 11:48:56.266401

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0292f11fadf5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiment_blueprints",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiment_blueprints")),
    )
    op.create_index(
        op.f("ix_experiment_blueprints_id"), "experiment_blueprints", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_experiment_blueprints_name"), "experiment_blueprints", ["name"], unique=False
    )
    op.create_table(
        "participant_profiles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("baseline_valence", sa.Float(), nullable=True),
        sa.Column("baseline_arousal", sa.Float(), nullable=True),
        sa.Column("phobias", sa.JSON(), nullable=True),
        sa.Column("familiar_media", sa.JSON(), nullable=True),
        sa.Column("preferences", sa.JSON(), nullable=True),
        sa.Column("is_excluded", sa.Boolean(), nullable=True),
        sa.Column("exclusion_reason", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participant_profiles")),
    )
    op.create_index(
        op.f("ix_participant_profiles_id"), "participant_profiles", ["id"], unique=False
    )
    op.create_table(
        "stimuli_metadata",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("uri", sa.String(), nullable=True),
        sa.Column("modality", sa.String(), nullable=True),
        sa.Column("content_tags", sa.JSON(), nullable=True),
        sa.Column("normative_valence", sa.Float(), nullable=True),
        sa.Column("normative_arousal", sa.Float(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stimuli_metadata")),
    )
    op.create_index(op.f("ix_stimuli_metadata_id"), "stimuli_metadata", ["id"], unique=False)
    op.create_index(
        op.f("ix_stimuli_metadata_modality"), "stimuli_metadata", ["modality"], unique=False
    )
    op.create_index(op.f("ix_stimuli_metadata_uri"), "stimuli_metadata", ["uri"], unique=False)
    op.create_table(
        "blueprint_phases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("blueprint_id", sa.String(), nullable=True),
        sa.Column("phase_order", sa.Integer(), nullable=True),
        sa.Column("target_valence", sa.Float(), nullable=True),
        sa.Column("target_arousal", sa.Float(), nullable=True),
        sa.Column("min_duration_ms", sa.Integer(), nullable=True),
        sa.Column("max_duration_ms", sa.Integer(), nullable=True),
        sa.Column("allowed_modalities", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["blueprint_id"],
            ["experiment_blueprints.id"],
            name=op.f("fk_blueprint_phases_blueprint_id_experiment_blueprints"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blueprint_phases")),
    )
    op.create_index(
        op.f("ix_blueprint_phases_blueprint_id"), "blueprint_phases", ["blueprint_id"], unique=False
    )
    op.create_index(op.f("ix_blueprint_phases_id"), "blueprint_phases", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_blueprint_phases_id"), table_name="blueprint_phases")
    op.drop_index(op.f("ix_blueprint_phases_blueprint_id"), table_name="blueprint_phases")
    op.drop_table("blueprint_phases")
    op.drop_index(op.f("ix_stimuli_metadata_uri"), table_name="stimuli_metadata")
    op.drop_index(op.f("ix_stimuli_metadata_modality"), table_name="stimuli_metadata")
    op.drop_index(op.f("ix_stimuli_metadata_id"), table_name="stimuli_metadata")
    op.drop_table("stimuli_metadata")
    op.drop_index(op.f("ix_participant_profiles_id"), table_name="participant_profiles")
    op.drop_table("participant_profiles")
    op.drop_index(op.f("ix_experiment_blueprints_name"), table_name="experiment_blueprints")
    op.drop_index(op.f("ix_experiment_blueprints_id"), table_name="experiment_blueprints")
    op.drop_table("experiment_blueprints")
    # ### end Alembic commands ###
